-- Obsoleto: o projeto usa RLS em Supabase/schema.sql.
-- Apagar linhas de vw_cost_audit_enriched / cost_entries_audit no app exige sessão
-- de usuário com linha em app_profiles (role admin). Veja admin_profile_setup.sql.
